services:
  redis:
    image: redis:8.2.0-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"] # persistence enabled
    container_name: redis

volumes:
  redis-data:
