# https://taskfile.dev

version: '3'

dotenv:
  - .env

tasks:
  compose:up:
    desc: "run all docker services"
    cmd: docker compose up -d

  compose:down:
    desc: "stop all docker services"
    cmd: docker compose down

  db:cli:
    desc: "access postgres db through cli"
    cmd: docker exec -it postgres psql -U {{ .DB_USER }} -b {{ .DB_NAME }}

  dev:order:
    desc: "run order service in dev mode"
    cmd: go run services/order-service/main.go

  dev:inventory:
    desc: "run inventory service in dev mode"
    cmd: go run services/inventory-service/cmd/grpc/main.go

  gen:order:
    desc: "generate protobuf for order service"
    cmd: protoc --go_out=services/common/genproto/order --go_opt=paths=source_relative --go-grpc_out=services/common/genproto/order --go-grpc_opt=paths=source_relative protobuf/order.proto

  gen:inventory:
    desc: "generate protobuf for inventory service"
    cmd: protoc --go_out=services/common/genproto/inventory --go_opt=paths=source_relative --go-grpc_out=services/common/genproto/inventory --go-grpc_opt=paths=source_relative protobuf/inventory.proto