// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: protobuf/order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_protobuf_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_protobuf_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateOrderReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateOrderRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRes) Reset() {
	*x = CreateOrderRes{}
	mi := &file_protobuf_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRes) ProtoMessage() {}

func (x *CreateOrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRes.ProtoReflect.Descriptor instead.
func (*CreateOrderRes) Descriptor() ([]byte, []int) {
	return file_protobuf_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderRes) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_protobuf_order_proto protoreflect.FileDescriptor

const file_protobuf_order_proto_rawDesc = "" +
	"\n" +
	"\x14protobuf/order.proto\x12\x05order\"K\n" +
	"\x0eCreateOrderReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"(\n" +
	"\x0eCreateOrderRes\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2K\n" +
	"\fOrderService\x12;\n" +
	"\vCreateOrder\x12\x15.order.CreateOrderReq\x1a\x15.order.CreateOrderResBIZGgithub.com/yehezkiel1086/go-docs/go-grpc-order-inventory/protobuf/orderb\x06proto3"

var (
	file_protobuf_order_proto_rawDescOnce sync.Once
	file_protobuf_order_proto_rawDescData []byte
)

func file_protobuf_order_proto_rawDescGZIP() []byte {
	file_protobuf_order_proto_rawDescOnce.Do(func() {
		file_protobuf_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_order_proto_rawDesc), len(file_protobuf_order_proto_rawDesc)))
	})
	return file_protobuf_order_proto_rawDescData
}

var file_protobuf_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_order_proto_goTypes = []any{
	(*CreateOrderReq)(nil), // 0: order.CreateOrderReq
	(*CreateOrderRes)(nil), // 1: order.CreateOrderRes
}
var file_protobuf_order_proto_depIdxs = []int32{
	0, // 0: order.OrderService.CreateOrder:input_type -> order.CreateOrderReq
	1, // 1: order.OrderService.CreateOrder:output_type -> order.CreateOrderRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_order_proto_init() }
func file_protobuf_order_proto_init() {
	if File_protobuf_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_order_proto_rawDesc), len(file_protobuf_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_order_proto_goTypes,
		DependencyIndexes: file_protobuf_order_proto_depIdxs,
		MessageInfos:      file_protobuf_order_proto_msgTypes,
	}.Build()
	File_protobuf_order_proto = out.File
	file_protobuf_order_proto_goTypes = nil
	file_protobuf_order_proto_depIdxs = nil
}
