// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: protobuf/inventory.proto

package go_grpc_inventory_microservices

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Inventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     uint64                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	mi := &file_protobuf_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_protobuf_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Inventory) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Inventory) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Inventory) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Inventory) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Inventory) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetInventoryByProductIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryByProductIDRequest) Reset() {
	*x = GetInventoryByProductIDRequest{}
	mi := &file_protobuf_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryByProductIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryByProductIDRequest) ProtoMessage() {}

func (x *GetInventoryByProductIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryByProductIDRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryByProductIDRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *GetInventoryByProductIDRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetInventoryByProductIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *Inventory             `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryByProductIDResponse) Reset() {
	*x = GetInventoryByProductIDResponse{}
	mi := &file_protobuf_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryByProductIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryByProductIDResponse) ProtoMessage() {}

func (x *GetInventoryByProductIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryByProductIDResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryByProductIDResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *GetInventoryByProductIDResponse) GetInventory() *Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type GetInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryRequest) Reset() {
	*x = GetInventoryRequest{}
	mi := &file_protobuf_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryRequest) ProtoMessage() {}

func (x *GetInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *GetInventoryRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *Inventory             `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryResponse) Reset() {
	*x = GetInventoryResponse{}
	mi := &file_protobuf_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryResponse) ProtoMessage() {}

func (x *GetInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *GetInventoryResponse) GetInventory() *Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type CreateInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInventoryRequest) Reset() {
	*x = CreateInventoryRequest{}
	mi := &file_protobuf_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInventoryRequest) ProtoMessage() {}

func (x *CreateInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInventoryRequest.ProtoReflect.Descriptor instead.
func (*CreateInventoryRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *CreateInventoryRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateInventoryRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *Inventory             `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInventoryResponse) Reset() {
	*x = CreateInventoryResponse{}
	mi := &file_protobuf_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInventoryResponse) ProtoMessage() {}

func (x *CreateInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInventoryResponse.ProtoReflect.Descriptor instead.
func (*CreateInventoryResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *CreateInventoryResponse) GetInventory() *Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type UpdateInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     uint64                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInventoryRequest) Reset() {
	*x = UpdateInventoryRequest{}
	mi := &file_protobuf_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInventoryRequest) ProtoMessage() {}

func (x *UpdateInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInventoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateInventoryRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateInventoryRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateInventoryRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateInventoryRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *Inventory             `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInventoryResponse) Reset() {
	*x = UpdateInventoryResponse{}
	mi := &file_protobuf_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInventoryResponse) ProtoMessage() {}

func (x *UpdateInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInventoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateInventoryResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateInventoryResponse) GetInventory() *Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type DeleteInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInventoryRequest) Reset() {
	*x = DeleteInventoryRequest{}
	mi := &file_protobuf_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInventoryRequest) ProtoMessage() {}

func (x *DeleteInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInventoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteInventoryRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteInventoryRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInventoryResponse) Reset() {
	*x = DeleteInventoryResponse{}
	mi := &file_protobuf_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInventoryResponse) ProtoMessage() {}

func (x *DeleteInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInventoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteInventoryResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteInventoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_protobuf_inventory_proto protoreflect.FileDescriptor

const file_protobuf_inventory_proto_rawDesc = "" +
	"\n" +
	"\x18protobuf/inventory.proto\"\x94\x01\n" +
	"\tInventory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x04R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"?\n" +
	"\x1eGetInventoryByProductIDRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\"K\n" +
	"\x1fGetInventoryByProductIDResponse\x12(\n" +
	"\tinventory\x18\x01 \x01(\v2\n" +
	".InventoryR\tinventory\"%\n" +
	"\x13GetInventoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"@\n" +
	"\x14GetInventoryResponse\x12(\n" +
	"\tinventory\x18\x01 \x01(\v2\n" +
	".InventoryR\tinventory\"S\n" +
	"\x16CreateInventoryRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"C\n" +
	"\x17CreateInventoryResponse\x12(\n" +
	"\tinventory\x18\x01 \x01(\v2\n" +
	".InventoryR\tinventory\"c\n" +
	"\x16UpdateInventoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x04R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"C\n" +
	"\x17UpdateInventoryResponse\x12(\n" +
	"\tinventory\x18\x01 \x01(\v2\n" +
	".InventoryR\tinventory\"(\n" +
	"\x16DeleteInventoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"3\n" +
	"\x17DeleteInventoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xff\x02\n" +
	"\x10InventoryService\x12;\n" +
	"\fGetInventory\x12\x14.GetInventoryRequest\x1a\x15.GetInventoryResponse\x12D\n" +
	"\x0fCreateInventory\x12\x17.CreateInventoryRequest\x1a\x18.CreateInventoryResponse\x12D\n" +
	"\x0fUpdateInventory\x12\x17.UpdateInventoryRequest\x1a\x18.UpdateInventoryResponse\x12D\n" +
	"\x0fDeleteInventory\x12\x17.DeleteInventoryRequest\x1a\x18.DeleteInventoryResponse\x12\\\n" +
	"\x17GetInventoryByProductID\x12\x1f.GetInventoryByProductIDRequest\x1a .GetInventoryByProductIDResponseB:Z8github.com/yehezkiel1086/go-grpc-inventory-microservicesb\x06proto3"

var (
	file_protobuf_inventory_proto_rawDescOnce sync.Once
	file_protobuf_inventory_proto_rawDescData []byte
)

func file_protobuf_inventory_proto_rawDescGZIP() []byte {
	file_protobuf_inventory_proto_rawDescOnce.Do(func() {
		file_protobuf_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_inventory_proto_rawDesc), len(file_protobuf_inventory_proto_rawDesc)))
	})
	return file_protobuf_inventory_proto_rawDescData
}

var file_protobuf_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_protobuf_inventory_proto_goTypes = []any{
	(*Inventory)(nil),                       // 0: Inventory
	(*GetInventoryByProductIDRequest)(nil),  // 1: GetInventoryByProductIDRequest
	(*GetInventoryByProductIDResponse)(nil), // 2: GetInventoryByProductIDResponse
	(*GetInventoryRequest)(nil),             // 3: GetInventoryRequest
	(*GetInventoryResponse)(nil),            // 4: GetInventoryResponse
	(*CreateInventoryRequest)(nil),          // 5: CreateInventoryRequest
	(*CreateInventoryResponse)(nil),         // 6: CreateInventoryResponse
	(*UpdateInventoryRequest)(nil),          // 7: UpdateInventoryRequest
	(*UpdateInventoryResponse)(nil),         // 8: UpdateInventoryResponse
	(*DeleteInventoryRequest)(nil),          // 9: DeleteInventoryRequest
	(*DeleteInventoryResponse)(nil),         // 10: DeleteInventoryResponse
}
var file_protobuf_inventory_proto_depIdxs = []int32{
	0,  // 0: GetInventoryByProductIDResponse.inventory:type_name -> Inventory
	0,  // 1: GetInventoryResponse.inventory:type_name -> Inventory
	0,  // 2: CreateInventoryResponse.inventory:type_name -> Inventory
	0,  // 3: UpdateInventoryResponse.inventory:type_name -> Inventory
	3,  // 4: InventoryService.GetInventory:input_type -> GetInventoryRequest
	5,  // 5: InventoryService.CreateInventory:input_type -> CreateInventoryRequest
	7,  // 6: InventoryService.UpdateInventory:input_type -> UpdateInventoryRequest
	9,  // 7: InventoryService.DeleteInventory:input_type -> DeleteInventoryRequest
	1,  // 8: InventoryService.GetInventoryByProductID:input_type -> GetInventoryByProductIDRequest
	4,  // 9: InventoryService.GetInventory:output_type -> GetInventoryResponse
	6,  // 10: InventoryService.CreateInventory:output_type -> CreateInventoryResponse
	8,  // 11: InventoryService.UpdateInventory:output_type -> UpdateInventoryResponse
	10, // 12: InventoryService.DeleteInventory:output_type -> DeleteInventoryResponse
	2,  // 13: InventoryService.GetInventoryByProductID:output_type -> GetInventoryByProductIDResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_protobuf_inventory_proto_init() }
func file_protobuf_inventory_proto_init() {
	if File_protobuf_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_inventory_proto_rawDesc), len(file_protobuf_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_inventory_proto_goTypes,
		DependencyIndexes: file_protobuf_inventory_proto_depIdxs,
		MessageInfos:      file_protobuf_inventory_proto_msgTypes,
	}.Build()
	File_protobuf_inventory_proto = out.File
	file_protobuf_inventory_proto_goTypes = nil
	file_protobuf_inventory_proto_depIdxs = nil
}
