services:
  postgres:
    image: postgres:17-alpine
    restart: always
    #command: -c ssl=on -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: /var/lib/postgresql/data
    volumes:
    - ./data:/var/lib/postgresql/data
    ports:
    - '${DB_HOST}:${DB_PORT}:5432'
    container_name: postgres
