services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}        # Optional: Defaults to 'postgres'
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # Required: Set your password here
      POSTGRES_DB: ${DB_NAME}       # Optional: Creates this DB on startup
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    container_name: postgres

volumes:
  postgres_data:
